### ISSUE TITLE
Size Badge

### ISSUE THREAD

**Issue by ankitbeniwal** [RocktimSaikia/badge-it#1]
Hey @RocktimSaikia 

I was wondering if I can contribute by adding a simple size badge.

**Comment by rocktimsaikia** [comment]
@pagalprogrammer Sure. Since you are only suggesting a new `badge` request. I would suggest only sticking and making changes to the [/util.js](https://github.com/RocktimSaikia/badge-it/blob/b13b71902211bb5104eb5ecaa43f42b5efe576cd/util.js#L15) and not changing other parts of the code since I'm still optimizing and experimenting with some new features in another branch. Anyway, then I'm assigning this to you.

**Comment by ankitbeniwal** [comment]
As assigned, I have added two size badges. 
1. Repo Size
2. Code Size

I have also modified readme.md accordingly.

Refer to #5
